name: Publish package

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Setup credentials
        uses: fusion-engineering/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/

      - name: Install wasm-pack
        run: cargo install --git https://github.com/rustwasm/wasm-pack.git

      - name: Build
        run: wasm-pack build --scope crowdstress

      - name: Publish
        run: wasm-pack publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
